apiVersion: apps/v1
kind: Deployment
metadata:
  name: frontend
  labels:
    app: frontend
spec:
  replicas: 1
  selector:
    matchLabels:
      app: frontend
  template:
    metadata:
      labels:
        app: frontend
    spec:
      serviceAccountName: frontend-service-account  # Asociar el frontend con el ServiceAccount
      containers:
        - name: frontend
          image: oscargomezgonzalezz/frontend:v7
          ports:
            - containerPort: 80
