apiVersion: rbac.authorization.k8s.io/v1
kind: RoleBinding
metadata:
  name: mongodb-rolebinding
  namespace: default
subjects:
  - kind: ServiceAccount
    name: mongodb-service-account
    namespace: default
roleRef:
  kind: Role
  name: mongodb-role
  apiGroup: rbac.authorization.k8s.io
